---
- name: Setup Development Environment
  hosts: localhost
  become: yes
  vars:
    python_version: "3.11"
    node_version: "18.x"
    postgres_version: "14"
    redis_version: "7"

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - build-essential
          - python3-dev
          - libpq-dev
          - git
          - curl
        state: present
        update_cache: yes

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | sudo -E bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Create project directory
      file:
        path: "{{ ansible_env.HOME }}/projects/myapp"
        state: directory
        mode: '0755'

    - name: Clone repository
      git:
        repo: "https://github.com/your-org/myapp.git"
        dest: "{{ ansible_env.HOME }}/projects/myapp"
        version: main

    - name: Create virtual environment
      pip:
        name: virtualenv
        state: present

    - name: Setup Python virtual environment
      shell: |
        cd {{ ansible_env.HOME }}/projects/myapp
        python3 -m venv venv
      args:
        creates: "{{ ansible_env.HOME }}/projects/myapp/venv"

    - name: Install Python dependencies
      pip:
        name: "{{ item }}"
        state: present
      with_file: "{{ ansible_env.HOME }}/projects/myapp/requirements.txt"

    - name: Install Node.js dependencies
      npm:
        path: "{{ ansible_env.HOME }}/projects/myapp"
        state: present

    - name: Create .env file
      template:
        src: env.j2
        dest: "{{ ansible_env.HOME }}/projects/myapp/.env"
        mode: '0600'

    - name: Setup PostgreSQL database
      postgresql_db:
        name: myapp_dev
        state: present

    - name: Start Redis service
      service:
        name: redis-server
        state: started
        enabled: yes 