FROM python:3.13

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip && \
    pip install flask && \
    apt-get clean

WORKDIR /app
COPY hello_world.py /app
EXPOSE 5000

CMD ["python", "hello_world.py"]
