app:
  name: MyWebApp
  environment: production
  version: 1.0.0

server:
  host: 0.0.0.0
  port: 8080
  enable_https: true
  ssl_certificate_path: /etc/ssl/certs/mywebapp.crt
  ssl_key_path: /etc/ssl/private/mywebapp.key
  max_connections: 100

database:
  type: postgresql
  host: localhost
  port: 5432
  name: mywebapp_db
  user: mywebapp_user
  password: secure_password
  pool_size: 10
  timeout: 30

logging:
  level: info
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: /var/log/mywebapp/app.log
  max_file_size: 10MB
  max_backup_files: 5

features:
  enable_user_registration: true
  enable_email_notifications: true
  supported_languages:
    - en
    - es
    - fr
    - de
  maintenance_mode: false